language: rust
rust: [stable, beta, nightly]
cache: cargo

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] ; then rustup component add clippy-preview --toolchain=nightly ; fi'

script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] ; then cargo clippy ; else cargo build ; fi'
