format_code_in_doc_comments = true
format_macro_matchers = true
match_block_trailing_comma = true
merge_imports = true
normalize_doc_attributes = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
use_try_shorthand = true
