#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SipMessageError {
    MissingFromHeader,
    MissingToHeader,
    MissingViaHeader,
    MissingCallIdHeader,
    MissingCSeqHeader,
    MissingContactHeader,
    MissingExpiresHeader,
    MissingEventHeader,
    MissingFromTag,
    MissingToTag,
    MissingUriUsername,
    MissingFromUsername,
    MissingToUsername,
    MissingContactUsername,
    MissingMethod,
    MissingStatusCode,
    MissingViaBranch,
    MissingContactExpires,
    MissingRegisterExpires,
}
